server:
  port: 4000


spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  main:
    allow-bean-definition-overriding: true

  application:
    name: backend

  mail:
    host: ${MAILER_HOST}
    port: ${MAILER_PORT}
    username: ${MAILER_USERNAME}
    password: ${MAILER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  r2dbc:
    url: r2dbc:mariadb://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50


  sql:
    init:
      mode: always
      platform: mariadb
      schema-locations: classpath:schema.sql


springdoc:
  swagger-ui:
    path: /


jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  expiration:
    time: ${JWT_EXPIRATION_TIME}


payments:
  tpay:
    api_url: ${PAYMENTS_TPAY_API_URL}
    client_id: ${PAYMENTS_TPAY_CLIENT_ID}
    client_secret: ${PAYMENTS_TPAY_CLIENT_SECRET}
    secret_sum_code: ${PAYMENTS_TPAY_SECRET_SUM_CODE}
    certs:
      jws_root: ${PAYMENTS_TPAY_CERTS_JWS_ROOT}
      jws_notifications: ${PAYMENTS_TPAY_CERTS_JWS_NOTIFICATIONS}


cdn:
  storage:
    path: ${CDN_STORAGE_PATH}
