spring:
  application:
    name: backend

  r2dbc:
    url: r2dbc:mariadb://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  sql:
    init:
      mode: always
      platform: mariadb
      schema-locations: classpath:schema.sql

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  expiration:
    time: ${JWT_EXPIRATION_TIME}
